highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
permalink: /:year/:month/:day/:title.html
name: "BoSs"

author: "xiaobo"
atom-baseurl: "http://rensisi.com"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.flickr.com/photos/86495645@N04/
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

